runtime: nodejs20

basic_scaling:
  max_instances: 11
  idle_timeout: 10m

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10 # Adjust based on your needs

network:
  session_affinity: true

handlers:
  - url: /.*
    script: auto

env_variables:
  JWT_SECRET: "asdfgnakfngandfgiaofjnwehruh2898934h2u42bhb2bubhu2ed2u"
  MONGODB_URI: "mongodb+srv://borgar90:yhV3OF0IhmUiEXvv@grandmasterssmith.7ohoasp.mongodb.net/Grandmasterssmith?retryWrites=true&w=majority"
  MONGODB_DB: "Grandmasterssmith"
  STREAM_API_KEY: "jdwsjxmg42zp"
  STREAM_SECRET: "9c6c27vfcwjfghb82ts2txtb5znfk3c8z572ena4v8qrpvus3uy3pkp4sexzwfj4"
  STREAM_ID: "1301212"
